### ISSUE TITLE
Frontend Setup with React

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/thindi-app#1]
Set up the frontend structure of the app using React.js. Create the basic folder structure and install the required dependencies (React, React Router, etc.).

**Comment by aparna-u** [comment]
Hi, I would like to take on this issue, Please assign this issue to me.

**Comment by n-keerthi-gayathri** [comment]
@arshadpatel please assign me this issue

**Comment by arshadpatel** [comment]
Hi @aparna-u and @n-keerthi-gayathri,

Thanks for your interest! You can both start working on this issue. We're happy to review all submitted PRs, and we'll merge the one that best fits the project's requirements and standards.

No need to wait for official assignment—feel free to begin and share your progress here. This way, we can give you feedback as you move along and officially assign the task once we've seen some progress.

Looking forward to your contributions!

**Comment by aparna-u** [comment]
Hi @arshadpatel , Please take a look at PR #12  and let me know if you have any suggestions.
