### ISSUE TITLE
Backend Setup with Node.js/Express

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/thindi-app#3]
Set up a basic Express server. Create initial routes for testing the server with a /status route that returns a simple "API is running" message.

**Comment by aparna-u** [comment]
I can take this issue, Please assign this issue to me.

**Comment by n-keerthi-gayathri** [comment]
@arshadpatel please assign me this issue

**Comment by arshadpatel** [comment]
Hi @aparna-u and @n-keerthi-gayathri,

Thanks for your interest! You can both start working on this issue. We're happy to review all submitted PRs, and we'll merge the one that best fits the project's requirements and standards.

No need to wait for official assignment—feel free to begin and share your progress here. This way, we can give you feedback as you move along and officially assign the task once we've seen some progress.
