### ISSUE TITLE
MongoDB Connection Setup (Backend)

### ISSUE THREAD

**Issue by arshadpatel** [arshadpatel/thindi-app#5]
et up MongoDB (using Mongoose) in the backend to connect to a local or Atlas database. Create a test connection and log success or failure.

**Comment by n-keerthi-gayathri** [comment]
@arshadpatel please assign me this issue

**Comment by arshadpatel** [comment]
No need to wait for official assignment—feel free to begin and share your progress here. This way, we can give you feedback as you move along and officially assign the task once we've seen some progress.

**Comment by n-keerthi-gayathri** [comment]
please close this issue @arshadpatel
